### ISSUE TITLE
Numerical results of reported plots

### ISSUE THREAD

**Issue by ybendou** [yangyangyang127/APE#12]
Hello, 

Thank you for the very interesting work! 

Could you please provide the numerical results of your reported experiments? I would really appreciate it! 

Also, is the performance you are reporting in the main plots using GPT3 templates or the regular CLIP template ('a photo of {class}')? 

Thanks in advance for you response! 

Best,

**Comment by yangyangyang127** [comment]
I have added a .pynb file which contains the detailed results.
Link: https://github.com/yangyangyang127/APE/blob/main/APE_results.ipynb

**Comment by ybendou** [comment]
Thanks!
